apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: onboarding
        envFrom:
          - configMapRef:
              name: onboarding-config
        image: quay.io/larsks/moc-acct-manager:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
      serviceAccountName: onboarding
