[tool.pylint.MESSAGES_CONTROL]
disable = 'invalid-name,too-few-public-methods'

[tool.mypy]
mypy_path = './stubs'
plugins = 'pydantic.mypy'
ignore_missing_imports = true
strict = true
implicit_reexport = true
