apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: onboarding
commonLabels:
  app: onboarding
resources:
- namespace.yaml
- clusterrolebinding.yaml
- deployment.yaml
- serviceaccount.yaml
- service.yaml
- route.yaml

configMapGenerator:
- name: onboarding-quotas
  files:
    - quotas.json
